project:
  output-dir: _output
  type: website

website:
  title: "Aerial Mzansi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    code-link: true
    include-in-header: "plausible.html"
    callout-appearance: simple
    toc: true
