project:
  output-dir: _output
  type: website

website:
  title: "Aerial Mzansi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: https://github.com/luisdza/aerialmzansi
        text: Source code
  twitter-card: true

format:
  html:
    theme: cosmo
    code-link: true
    include-in-header: "plausible.html"
    callout-appearance: simple
    toc: true
    author-meta: "Luis de Sousa"
    description-meta: "Aerial Mzansi"
